[project]
name = "linux-sysadmin-tools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "loguru>=0.7.3",
    "paramiko>=4.0.0",
    "ping3>=5.1.5",
    "psutil>=7.2.2",
    "schedule>=1.2.2",
]
